/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50524
Source Host           : localhost:3306
Source Database       : bd_unimed

Target Server Type    : MYSQL
Target Server Version : 50524
File Encoding         : 65001

Date: 2013-10-17 10:28:14
*/
USE bdunimed;

-- ----------------------------
-- Records of sis_acoes
-- ----------------------------
INSERT INTO `sis_acoes` VALUES ('1', 'visualizar');
INSERT INTO `sis_acoes` VALUES ('2', 'listar');
INSERT INTO `sis_acoes` VALUES ('4', 'inserir');
INSERT INTO `sis_acoes` VALUES ('8', 'editar');
INSERT INTO `sis_acoes` VALUES ('16', 'excluir');
INSERT INTO `sis_acoes` VALUES ('32', 'cancelar');
INSERT INTO `sis_acoes` VALUES ('64', 'importar');
INSERT INTO `sis_acoes` VALUES ('128', 'exportar');

-- ----------------------------
-- Records of sis_departamento
-- ----------------------------
INSERT INTO `sis_departamento` VALUES ('1', 'Principal', null);

-- ----------------------------
-- Records of sis_equipe
-- ----------------------------
INSERT INTO `sis_equipe` VALUES ('1', 'Administrador', '2', '2013-10-17 16:29:42', null, null, '0', '0', '0');
INSERT INTO `sis_equipe` VALUES ('2', 'Unimed', '0', '2013-10-17 12:27:39', null, null, '0', '0', '0');

-- ----------------------------
-- Records of sis_equipe_config
-- ----------------------------
INSERT INTO `sis_equipe_config` VALUES ('1', 'logo_cliente.png', '1', 'webtupi', '1', null, null, null, null, null, null);

-- ----------------------------
-- Records of sis_menu
-- ----------------------------
INSERT INTO `sis_menu` VALUES ('1', null, '1', 'Home', 'index.php', null, '1', '0', '2013-10-15 13:17:48');
INSERT INTO `sis_menu` VALUES ('2', null, '1', 'Sobre a Unimed', 'quemsomos.php', null, '1', '0', '2013-10-15 13:18:26');
INSERT INTO `sis_menu` VALUES ('3', null, '1', 'Trabalhe Conosco', 'trabalheConosco.php', null, '1', '0', '2013-10-15 13:18:51');
INSERT INTO `sis_menu` VALUES ('4', null, '1', 'Mapa do Site', 'mapa.php', null, '1', '0', '2013-10-15 13:19:07');
INSERT INTO `sis_menu` VALUES ('5', null, '1', 'Sac', 'sac.php', null, '1', '1', '2013-10-15 13:19:20');
INSERT INTO `sis_menu` VALUES ('6', null, '1', 'Ouvidoria', 'ouvidoria.php', null, '1', '0', '2013-10-15 13:20:11');
INSERT INTO `sis_menu` VALUES ('7', null, '1', 'Clientes', 'clientesHome.php', null, '1', '0', '2013-10-15 13:20:35');
INSERT INTO `sis_menu` VALUES ('8', '7', '1', 'Seja um Cliente', 'sejaUmCliente.php', null, '1', '0', '2013-10-15 13:21:08');
INSERT INTO `sis_menu` VALUES ('9', '7', '1', 'Guia Medico', 'clientesGuia.php', null, '1', '0', '2013-10-15 13:22:10');
INSERT INTO `sis_menu` VALUES ('10', '7', '1', 'Eventos', 'clientesEventos.php', null, '1', '0', '2013-10-15 13:22:41');
INSERT INTO `sis_menu` VALUES ('11', '7', '1', '2 Via Boleto Pessoa Física', 'clientesSegundaViaPf.php', null, '1', '1', '2013-10-15 13:23:10');
INSERT INTO `sis_menu` VALUES ('12', '7', '1', '2 Via Boleto Pessoa Juridica', 'clientesSegundaViaPj.php', null, '1', '1', '2013-10-15 13:23:44');
INSERT INTO `sis_menu` VALUES ('13', '7', '1', 'Noticias', 'clientesNoticias.php', null, '1', '0', '2013-10-15 13:24:09');
INSERT INTO `sis_menu` VALUES ('14', '7', '1', 'Debito Automático', 'clientesDebitoAut.php', null, '1', '1', '2013-10-15 13:24:51');
INSERT INTO `sis_menu` VALUES ('15', '7', '1', 'Enquete', 'clientesEnquete.php', null, '1', '0', '2013-10-15 13:25:15');
INSERT INTO `sis_menu` VALUES ('16', '7', '1', 'Atualização de Dados', 'clientesAtualizacao.php', null, '1', '1', '2013-10-15 13:26:37');
INSERT INTO `sis_menu` VALUES ('17', '7', '1', 'Trabalhe Conosco', 'trabalheConosco.php', null, '1', '1', '2013-10-15 13:26:58');
INSERT INTO `sis_menu` VALUES ('18', '7', '1', 'Extrato de Utilização', 'clientesExtrato.php', null, '1', '0', '2013-10-15 13:27:18');
INSERT INTO `sis_menu` VALUES ('19', '7', '1', 'Informe IR', 'clientesInformeIR.php', null, '1', '0', '2013-10-15 13:27:40');
INSERT INTO `sis_menu` VALUES ('20', '7', '1', 'Demonstrativo de Repasse', 'clientesRepasse.php', null, '1', '0', '2013-10-15 13:28:04');
INSERT INTO `sis_menu` VALUES ('21', '7', '1', 'Sac', 'clientesSac.php', null, '1', '1', '2013-10-15 13:28:28');
INSERT INTO `sis_menu` VALUES ('22', null, '1', 'Cooperados', 'cooperadosHome.php', null, '1', '0', '2013-10-16 21:30:38');
INSERT INTO `sis_menu` VALUES ('23', '22', '1', 'Agenda de Compromissos', 'cooperadosAgendaEventos.php', null, '1', '0', '2013-10-16 21:34:39');
INSERT INTO `sis_menu` VALUES ('24', '22', '1', 'Tabela CHBPM', 'cooperadosTabelaCHBPM.php', null, '1', '0', '2013-10-16 21:35:19');
INSERT INTO `sis_menu` VALUES ('25', '22', '1', 'Calendário', 'cooperadosCalendarioPagamentos.php', null, '1', '0', '2013-10-16 21:35:45');
INSERT INTO `sis_menu` VALUES ('26', '22', '1', 'CID', 'cooperadosCID.php', null, '1', '0', '2013-10-16 21:36:07');
INSERT INTO `sis_menu` VALUES ('27', '22', '1', 'Tabela TNUMM', 'cooperadosTabelaTnumm.php', null, '1', '0', '2013-10-16 21:36:30');
INSERT INTO `sis_menu` VALUES ('28', '22', '1', 'Tabela TUSS', 'cooperadosTabelaTuss.php', null, '1', '0', '2013-10-16 21:36:53');
INSERT INTO `sis_menu` VALUES ('29', '22', '1', 'Indicação Artigos', 'cooperadosIndecacaoArtigos.php', null, '1', '0', '2013-10-16 21:37:17');
INSERT INTO `sis_menu` VALUES ('30', '22', '1', 'Produção Médica', 'cooperadosProducaoMedica.php', null, '1', '0', '2013-10-16 21:37:39');
INSERT INTO `sis_menu` VALUES ('31', '22', '1', 'Tutorial HILUM', 'cooperadosTutorialHilum.php', null, '1', '0', '2013-10-16 21:38:01');
INSERT INTO `sis_menu` VALUES ('32', '22', '1', 'Manual do Cooperado', 'cooperadosManual.php', null, '1', '0', '2013-10-16 21:38:25');
INSERT INTO `sis_menu` VALUES ('33', '22', '1', 'Notícias', 'cooperadosNoticias.php', null, '1', '0', '2013-10-16 21:38:47');
INSERT INTO `sis_menu` VALUES ('34', '22', '1', 'Informe IR', 'cooperadosInformeIR.php', null, '1', '0', '2013-10-16 21:39:07');
INSERT INTO `sis_menu` VALUES ('35', '22', '1', 'Enquete', 'cooperadosEnquete.php', null, '1', '0', '2013-10-16 21:39:27');
INSERT INTO `sis_menu` VALUES ('36', '22', '1', 'Segunda Via de Cartão', 'cooperadosSegundaVia.php', null, '1', '0', '2013-10-16 21:40:06');
INSERT INTO `sis_menu` VALUES ('37', '22', '1', 'TISS', 'cooperadosTiss.php', null, '1', '0', '2013-10-16 21:40:27');
INSERT INTO `sis_menu` VALUES ('38', '22', '1', 'SLIP', 'cooperadosSlip.php', null, '1', '0', '2013-10-16 21:40:45');
INSERT INTO `sis_menu` VALUES ('39', '22', '1', 'Fórum', 'cooperadosForum.php', null, '1', '0', '2013-10-16 21:41:17');
INSERT INTO `sis_menu` VALUES ('40', '22', '1', 'Sac', 'sac.php', null, '1', '0', '2013-10-16 21:41:40');
INSERT INTO `sis_menu` VALUES ('41', null, '1', 'Secretárias', 'secretariasHome.php', null, '1', '0', '2013-10-16 21:42:11');
INSERT INTO `sis_menu` VALUES ('42', '41', '1', 'Notícias', 'secretariasNoticias.php', null, '1', '0', '2013-10-16 21:42:35');
INSERT INTO `sis_menu` VALUES ('43', '41', '1', 'Calendário', 'secretariasCalendario.php', null, '1', '0', '2013-10-16 21:42:55');
INSERT INTO `sis_menu` VALUES ('44', '41', '1', 'Enquete', 'secretariasEnquete.php', null, '1', '0', '2013-10-16 21:43:11');
INSERT INTO `sis_menu` VALUES ('45', '41', '1', 'Solicitações', 'secretariasSolicitacoes.php', null, '1', '0', '2013-10-16 21:43:32');
INSERT INTO `sis_menu` VALUES ('46', '41', '1', 'Autorizações', 'secretariasAutorizacoes.php', null, '1', '0', '2013-10-16 21:44:00');
INSERT INTO `sis_menu` VALUES ('47', '41', '1', 'Sac', 'sac.php', null, '1', '0', '2013-10-16 21:44:26');
INSERT INTO `sis_menu` VALUES ('48', null, '1', 'Credenciados', 'credenciadosHome.php', null, '1', '0', '2013-10-16 21:45:12');
INSERT INTO `sis_menu` VALUES ('49', '48', '1', 'Enquete', 'credenciadosEnquete.php', null, '1', '0', '2013-10-16 21:45:36');
INSERT INTO `sis_menu` VALUES ('50', '48', '1', 'Calendário', 'credenciadosCalendario.php', null, '1', '0', '2013-10-16 21:46:04');
INSERT INTO `sis_menu` VALUES ('51', '48', '1', 'Notícias', 'credenciadosNoticias.php', null, '1', '0', '2013-10-16 21:46:24');
INSERT INTO `sis_menu` VALUES ('52', '48', '1', 'Sac', 'sac.php', null, '1', '0', '2013-10-16 21:46:46');
INSERT INTO `sis_menu` VALUES ('53', null, '1', 'Colaboradores', 'colaboradoresHome.php', null, '1', '0', '2013-10-16 21:47:33');
INSERT INTO `sis_menu` VALUES ('54', '53', '1', 'Sinistrômetro', 'colaboradoresSinistrometro.php', null, '1', '0', '2013-10-16 21:48:35');
INSERT INTO `sis_menu` VALUES ('55', '53', '1', 'Galeria de Fotos', 'colaboradoresGaleriaFotos.php', null, '1', '0', '2013-10-16 21:49:26');
INSERT INTO `sis_menu` VALUES ('56', '53', '1', 'Calendário', 'colaboradoresCalendario.php', null, '1', '0', '2013-10-16 21:49:45');
INSERT INTO `sis_menu` VALUES ('57', '53', '1', 'Jornal Cara A Cara', 'colaboradoresJornalCaraACara.php', null, '1', '0', '2013-10-16 21:50:13');
INSERT INTO `sis_menu` VALUES ('58', '53', '1', 'Notícias', 'colaboradoresNoticias.php', null, '1', '0', '2013-10-16 21:50:33');
INSERT INTO `sis_menu` VALUES ('59', '53', '1', 'Webmail', 'correio.unimeduberlandia.com.br', null, '1', '0', '2013-10-16 21:52:29');
INSERT INTO `sis_menu` VALUES ('60', '53', '1', 'GED', 'http://ged.unimeduberlandia.com.br:8080/josso/signon/login.do?josso_back_to=http://ged.unimeduberlan', null, '1', '0', '2013-10-16 21:52:45');
INSERT INTO `sis_menu` VALUES ('61', '53', '1', 'GLPI', 'http://glpi.unimeduberlandia.com.br/', null, '1', '0', '2013-10-16 21:55:29');
INSERT INTO `sis_menu` VALUES ('62', '53', '1', 'GW', 'http://gw.unimeduberlandia.com.br:8080/gw/', null, '1', '0', '2013-10-16 21:55:54');
INSERT INTO `sis_menu` VALUES ('63', '53', '1', 'UNIATEND WEB', 'http://sistemas:8090/uniatend/', null, '1', '0', '2013-10-16 21:56:18');
INSERT INTO `sis_menu` VALUES ('64', '53', '1', 'UNIAGENDA WEB', 'http://sistemasweb.unimeduberlandia.coop.br/uniagenda/login.php', null, '1', '0', '2013-10-16 21:56:40');
INSERT INTO `sis_menu` VALUES ('65', '53', '1', 'SISTEMA DE CAIXA WEB', 'http://10.14.0.30/caixa/', null, '1', '0', '2013-10-16 21:56:57');
INSERT INTO `sis_menu` VALUES ('66', '53', '1', 'RH3', 'http://colaborador/portal', null, '1', '0', '2013-10-16 21:57:19');
INSERT INTO `sis_menu` VALUES ('67', '53', '1', 'CRM', 'http://crm.unimeduberlandia.com.br/', null, '1', '0', '2013-10-16 21:57:35');
INSERT INTO `sis_menu` VALUES ('68', '53', '1', 'Forum', 'http://forum.unimeduberlandia.com.br/', null, '1', '0', '2013-10-16 21:59:04');
INSERT INTO `sis_menu` VALUES ('69', '53', '1', 'Relatorios Cardio', 'http://10.14.0.30/mhs/relatorios/', null, '1', '0', '2013-10-16 21:59:22');
INSERT INTO `sis_menu` VALUES ('70', '53', '1', 'Sac', 'sac.php', null, '1', '0', '2013-10-16 21:59:40');

-- ----------------------------
-- Records of sis_perfil
-- ----------------------------
INSERT INTO `sis_perfil` VALUES ('1', 'Administrador', '1', 'Todos Modulos', '2013-10-17 16:29:42', null);
INSERT INTO `sis_perfil` VALUES ('2', 'Site - Colaboradores', '1', '', '2013-10-17 15:09:12', null);
INSERT INTO `sis_perfil` VALUES ('3', 'Site - Clientes', '1', '', '2013-10-17 15:09:58', null);
INSERT INTO `sis_perfil` VALUES ('4', 'Site - Cooperados', '1', '', '2013-10-17 15:10:41', null);
INSERT INTO `sis_perfil` VALUES ('5', 'Site - Secretarias', '1', '', '2013-10-17 15:11:04', null);
INSERT INTO `sis_perfil` VALUES ('6', 'Site - Credenciados', '1', '', '2013-10-17 15:11:20', null);
INSERT INTO `sis_perfil` VALUES ('7', 'Site - Geral', '1', '', '2013-10-17 15:38:54', null);
INSERT INTO `sis_perfil` VALUES ('8', 'Unimed Administrador', '1', '', '2013-10-15 16:44:16', null);

-- ----------------------------
-- Records of sis_perfil_permissoes
-- ----------------------------
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '1');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '2');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '3');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '4');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '5');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '6');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '7');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '8');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '9');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '10');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '11');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '12');
INSERT INTO `sis_perfil_permissoes` VALUES ('203', '1', '13');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '14');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '15');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '16');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '17');
INSERT INTO `sis_perfil_permissoes` VALUES ('243', '1', '18');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '19');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '20');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '21');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '22');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '23');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '24');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '25');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '26');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '27');
INSERT INTO `sis_perfil_permissoes` VALUES ('243', '1', '28');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '29');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '30');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '31');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '32');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '33');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '34');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '35');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '36');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '37');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '38');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '39');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '40');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '41');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '42');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '43');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '44');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '45');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '46');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '47');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '48');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '49');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '50');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '51');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '52');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '53');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '54');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '55');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '56');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '57');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '58');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '59');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '60');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '64');
INSERT INTO `sis_perfil_permissoes` VALUES ('255', '1', '65');

-- ----------------------------
-- Records of sis_permissoes
-- ----------------------------
INSERT INTO `sis_permissoes` VALUES ('1', 'AGENDA COMPROMISSO', '1');
INSERT INTO `sis_permissoes` VALUES ('2', 'ATIVIDADE PROFISSIONAL', '0');
INSERT INTO `sis_permissoes` VALUES ('3', 'CBHPM', '1');
INSERT INTO `sis_permissoes` VALUES ('4', 'CERTIFICACAO ESPECIALIZACAO', '0');
INSERT INTO `sis_permissoes` VALUES ('5', 'CERTIFICACAO HAS PROFISSIONAL', '0');
INSERT INTO `sis_permissoes` VALUES ('6', 'CID', '1');
INSERT INTO `sis_permissoes` VALUES ('7', 'CLIENTE', '1');
INSERT INTO `sis_permissoes` VALUES ('8', 'CLIENTE CARDIO', '0');
INSERT INTO `sis_permissoes` VALUES ('9', 'CLIENTE OBS', '0');
INSERT INTO `sis_permissoes` VALUES ('10', 'CLIENTE SITE', '1');
INSERT INTO `sis_permissoes` VALUES ('11', 'CONHECIMENTO HAS PROFISSIONAL', '0');
INSERT INTO `sis_permissoes` VALUES ('12', 'CONHECIMENTO TECNICO', '0');
INSERT INTO `sis_permissoes` VALUES ('13', 'DEBITO AUTOMATICO', '1');
INSERT INTO `sis_permissoes` VALUES ('14', 'DUVIDA', '1');
INSERT INTO `sis_permissoes` VALUES ('15', 'ENQUETE', '1');
INSERT INTO `sis_permissoes` VALUES ('16', 'ENQUETE ALTERNATIVA', '0');
INSERT INTO `sis_permissoes` VALUES ('17', 'ENQUETE PERMITIDO', '0');
INSERT INTO `sis_permissoes` VALUES ('18', 'ENQUETE VOTACAO', '0');
INSERT INTO `sis_permissoes` VALUES ('19', 'EVENTO', '1');
INSERT INTO `sis_permissoes` VALUES ('20', 'GALERIA DE FOTOS', '1');
INSERT INTO `sis_permissoes` VALUES ('21', 'EVENTO IMAGEM PERMITIDO', '0');
INSERT INTO `sis_permissoes` VALUES ('22', 'EVENTO PERMITIDO', '0');
INSERT INTO `sis_permissoes` VALUES ('23', 'EVENTO TIPO', '0');
INSERT INTO `sis_permissoes` VALUES ('24', 'EVENTO UPLOAD', '1');
INSERT INTO `sis_permissoes` VALUES ('25', 'EXTRA CURRICULAR', '0');
INSERT INTO `sis_permissoes` VALUES ('26', 'EXTRA CURRICULAR HAS PROFISSIONAL', '0');
INSERT INTO `sis_permissoes` VALUES ('27', 'FORMACAO', '0');
INSERT INTO `sis_permissoes` VALUES ('28', 'FORUM', '1');
INSERT INTO `sis_permissoes` VALUES ('29', 'FORUM COMENTARIO', '0');
INSERT INTO `sis_permissoes` VALUES ('30', 'HILUM', '1');
INSERT INTO `sis_permissoes` VALUES ('31', 'JORNAL', '1');
INSERT INTO `sis_permissoes` VALUES ('32', 'JORNAL IMAGEM', '0');
INSERT INTO `sis_permissoes` VALUES ('33', 'JORNALPERMITIDO', '0');
INSERT INTO `sis_permissoes` VALUES ('34', 'MANUALCOOPERADO', '1');
INSERT INTO `sis_permissoes` VALUES ('35', 'NOTICIA', '1');
INSERT INTO `sis_permissoes` VALUES ('36', 'NOTICIA IMAGEM', '0');
INSERT INTO `sis_permissoes` VALUES ('37', 'PRODUCAO MEDICA', '1');
INSERT INTO `sis_permissoes` VALUES ('38', 'REDESSOCIAIS', '0');
INSERT INTO `sis_permissoes` VALUES ('39', 'SAC', '1');
INSERT INTO `sis_permissoes` VALUES ('40', 'SAC ATENDIMENTOS', '0');
INSERT INTO `sis_permissoes` VALUES ('41', 'SAC SITE', '0');
INSERT INTO `sis_permissoes` VALUES ('42', 'SINISTROMETRO', '1');
INSERT INTO `sis_permissoes` VALUES ('43', 'SOLICITA BOLETO', '1');
INSERT INTO `sis_permissoes` VALUES ('44', 'SOLICITA CARTAO', '1');
INSERT INTO `sis_permissoes` VALUES ('45', 'TISS', '1');
INSERT INTO `sis_permissoes` VALUES ('46', 'TRABALHE CONOSCO', '1');
INSERT INTO `sis_permissoes` VALUES ('47', 'TRABALHE HAS ATIVIDADE', '0');
INSERT INTO `sis_permissoes` VALUES ('48', 'TUSS', '1');
INSERT INTO `sis_permissoes` VALUES ('49', 'BANNER', '1');
INSERT INTO `sis_permissoes` VALUES ('50', 'BANNER TIPO', '0');
INSERT INTO `sis_permissoes` VALUES ('51', 'SISACOES', '0');
INSERT INTO `sis_permissoes` VALUES ('52', 'SISEQUIPE', '0');
INSERT INTO `sis_permissoes` VALUES ('53', 'SISEQUIPECONFIGURACOES', '0');
INSERT INTO `sis_permissoes` VALUES ('54', 'PERFIL', '1');
INSERT INTO `sis_permissoes` VALUES ('55', 'SISPERMISSOES', '0');
INSERT INTO `sis_permissoes` VALUES ('56', 'SISPERMISSOESHASSISACOES', '0');
INSERT INTO `sis_permissoes` VALUES ('57', 'USUARIO', '1');
INSERT INTO `sis_permissoes` VALUES ('58', 'SISUSUARIOCONFIGS', '0');
INSERT INTO `sis_permissoes` VALUES ('59', 'SITE - EVENTO CLIENTES', '1');
INSERT INTO `sis_permissoes` VALUES ('60', 'SITE - EVENTO COOPERADOS', '1');
INSERT INTO `sis_permissoes` VALUES ('61', 'SITE - EVENTO SECRETARIAS', '1');
INSERT INTO `sis_permissoes` VALUES ('62', 'SITE - EVENTO CREDENCIADOS', '1');
INSERT INTO `sis_permissoes` VALUES ('63', 'SITE - EVENTO COLABORADORES', '1');
INSERT INTO `sis_permissoes` VALUES ('64', 'TNUMM', '1');
INSERT INTO `sis_permissoes` VALUES ('65', 'INDICACAO ARTIGO', '1');

-- ----------------------------
-- Records of sis_permissoes_equipe
-- ----------------------------
-- ----------------------------
-- Records of sis_permissoes_has_sis_acoes
-- ----------------------------
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('1', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('1', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('1', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('1', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('1', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('1', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('1', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('1', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('2', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('2', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('2', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('2', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('2', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('2', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('2', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('2', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('3', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('3', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('3', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('3', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('3', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('3', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('3', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('3', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('4', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('4', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('4', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('4', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('4', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('4', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('4', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('4', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('5', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('5', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('5', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('5', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('5', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('5', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('5', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('5', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('6', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('6', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('6', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('6', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('6', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('6', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('6', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('6', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('7', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('7', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('7', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('7', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('7', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('7', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('7', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('7', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('8', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('8', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('8', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('8', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('8', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('8', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('8', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('8', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('9', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('9', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('9', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('9', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('9', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('9', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('9', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('9', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('10', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('10', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('10', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('10', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('10', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('10', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('10', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('10', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('11', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('11', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('11', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('11', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('11', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('11', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('11', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('11', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('12', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('12', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('12', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('12', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('12', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('12', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('12', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('12', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('13', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('13', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('13', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('13', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('13', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('14', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('14', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('14', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('14', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('14', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('14', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('14', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('14', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('15', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('15', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('15', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('15', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('15', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('15', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('15', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('15', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('16', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('16', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('16', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('16', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('16', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('16', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('16', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('16', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('17', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('17', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('17', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('17', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('17', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('17', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('17', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('17', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('18', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('18', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('18', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('18', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('18', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('18', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('18', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('18', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('19', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('19', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('19', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('19', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('19', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('19', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('19', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('19', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('20', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('20', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('20', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('20', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('20', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('20', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('20', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('20', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('21', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('21', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('21', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('21', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('21', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('21', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('21', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('21', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('22', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('22', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('22', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('22', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('22', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('22', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('22', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('22', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('23', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('23', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('23', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('23', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('23', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('23', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('23', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('23', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('24', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('24', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('24', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('24', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('24', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('24', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('24', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('24', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('25', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('25', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('25', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('25', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('25', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('25', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('25', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('25', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('26', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('26', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('26', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('26', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('26', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('26', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('26', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('26', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('27', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('27', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('27', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('27', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('27', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('27', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('27', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('27', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('28', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('28', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('28', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('28', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('28', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('28', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('29', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('29', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('29', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('29', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('29', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('29', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('29', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('29', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('30', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('30', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('30', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('30', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('30', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('30', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('30', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('30', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('31', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('31', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('31', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('31', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('31', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('31', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('31', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('31', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('32', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('32', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('32', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('32', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('32', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('32', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('32', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('32', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('33', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('33', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('33', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('33', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('33', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('33', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('33', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('33', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('34', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('34', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('34', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('34', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('34', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('34', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('34', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('34', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('35', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('35', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('35', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('35', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('35', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('35', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('35', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('35', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('36', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('36', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('36', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('36', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('36', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('36', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('36', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('36', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('37', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('37', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('37', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('37', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('37', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('37', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('37', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('37', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('38', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('38', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('38', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('38', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('38', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('38', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('38', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('38', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('39', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('39', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('39', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('39', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('39', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('39', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('39', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('40', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('40', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('40', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('40', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('40', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('40', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('40', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('40', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('41', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('41', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('41', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('41', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('41', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('41', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('41', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('41', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('42', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('42', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('42', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('42', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('42', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('42', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('42', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('42', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('43', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('43', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('43', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('43', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('43', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('43', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('43', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('43', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('44', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('44', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('44', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('44', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('44', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('44', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('44', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('44', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('45', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('45', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('45', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('45', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('45', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('45', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('45', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('45', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('46', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('46', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('46', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('46', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('46', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('46', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('46', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('46', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('47', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('47', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('47', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('47', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('47', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('47', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('47', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('47', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('48', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('48', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('48', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('48', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('48', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('48', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('48', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('48', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('49', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('49', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('49', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('49', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('49', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('49', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('49', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('49', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('50', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('50', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('50', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('50', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('50', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('50', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('50', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('50', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('51', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('51', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('51', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('51', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('51', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('51', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('51', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('51', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('52', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('52', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('52', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('52', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('52', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('52', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('52', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('52', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('53', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('53', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('53', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('53', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('53', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('53', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('53', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('53', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('54', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('54', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('54', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('54', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('54', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('54', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('54', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('54', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('55', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('55', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('55', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('55', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('55', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('55', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('55', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('55', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('56', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('56', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('56', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('56', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('56', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('56', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('56', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('56', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('57', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('57', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('57', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('57', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('57', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('57', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('57', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('57', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('58', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('58', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('58', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('58', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('58', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('58', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('58', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('58', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('59', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('59', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('59', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('59', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('59', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('59', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('59', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('59', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('60', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('60', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('60', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('60', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('60', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('60', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('60', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('60', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('61', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('61', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('61', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('61', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('61', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('61', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('61', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('61', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('62', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('62', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('62', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('62', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('62', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('62', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('62', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('62', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('63', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('63', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('63', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('63', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('63', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('63', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('63', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('63', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('64', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('64', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('64', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('64', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('64', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('64', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('64', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('64', '128');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('65', '1');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('65', '2');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('65', '4');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('65', '8');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('65', '16');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('65', '32');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('65', '64');
INSERT INTO `sis_permissoes_has_sis_acoes` VALUES ('65', '128');

-- ----------------------------
-- Records of sis_usuario
-- ----------------------------
INSERT INTO `sis_usuario` VALUES ('1', '1', 'admin', 'admin', 'b1ef56a986b84e03847fb219871c8ea3', 'contato@webtupi.com.br', '2013-08-09 12:24:28', null, '1', '1', '0', '2013-10-16 20:40:03');
INSERT INTO `sis_usuario` VALUES ('2', '1', 'AdmUnimed', 'adminunimed', 'ad946354e21c57b5ece5dec5d0e0eb86', 'admin@unimed.com.br', '2013-08-09 14:30:01', null, '1', '1', '0', '2013-06-11 14:56:46');

-- ----------------------------
-- Records of sis_usuario_configs
-- ----------------------------

-- ----------------------------
-- Records of tab_banner_tipo
-- ----------------------------
INSERT INTO `tab_banner_tipo` VALUES ('1', '1', 'Geral', '2013-10-16 01:51:53', '2013-10-16 01:51:41');
INSERT INTO `tab_banner_tipo` VALUES ('2', '1', 'Colaboradores', '2013-09-07 13:30:30', null);
INSERT INTO `tab_banner_tipo` VALUES ('3', '1', 'Clientes', '2013-09-07 13:30:38', null);
INSERT INTO `tab_banner_tipo` VALUES ('4', '1', 'Cooperados', '2013-09-07 13:30:45', null);
INSERT INTO `tab_banner_tipo` VALUES ('5', '1', 'Secretarias', '2013-09-07 13:30:59', null);
INSERT INTO `tab_banner_tipo` VALUES ('6', '1', 'Credenciados', '2013-09-07 13:31:15', null);
INSERT INTO `tab_banner_tipo` VALUES ('7', '1', 'Home', '2013-10-16 01:51:40', null);

-- ----------------------------
-- Records of tab_cliente_tipo
-- ----------------------------
INSERT INTO `tab_cliente_tipo` VALUES ('1', 'Geral Site');
INSERT INTO `tab_cliente_tipo` VALUES ('2', 'Colaborador');
INSERT INTO `tab_cliente_tipo` VALUES ('3', 'Cliente');
INSERT INTO `tab_cliente_tipo` VALUES ('4', 'Cooperados');
INSERT INTO `tab_cliente_tipo` VALUES ('5', 'Secretarias');
INSERT INTO `tab_cliente_tipo` VALUES ('6', 'Credenciados');

-- ----------------------------
-- Records of tab_evento_tipo
-- ----------------------------
INSERT INTO `tab_evento_tipo` VALUES ('1', 'Evento', '2013-08-08 20:08:31', null);
INSERT INTO `tab_evento_tipo` VALUES ('2', 'Entrega de notas', '2013-08-08 20:08:31', null);
INSERT INTO `tab_evento_tipo` VALUES ('3', 'Pagamentos', '2013-08-08 20:08:31', null);

-- ----------------------------
-- Records of tab_formacao
-- ----------------------------
INSERT INTO `tab_formacao` VALUES ('1', 'Graduacao', '2013-08-08 20:08:31', null);
INSERT INTO `tab_formacao` VALUES ('2', 'Pos-graduacao', '2013-08-08 20:08:31', null);
INSERT INTO `tab_formacao` VALUES ('3', 'MBA', '2013-08-08 20:08:31', null);
INSERT INTO `tab_formacao` VALUES ('4', 'Mestrado', '2013-08-08 20:08:31', null);
INSERT INTO `tab_formacao` VALUES ('5', 'Doutorado', '2013-08-08 20:08:31', null);
INSERT INTO `tab_formacao` VALUES ('6', 'Pos-doutorado', '2013-08-08 20:08:31', null);
INSERT INTO `tab_formacao` VALUES ('7', 'Tecnico', '2013-08-08 20:08:31', null);
INSERT INTO `tab_formacao` VALUES ('8', 'Ensino Medio', '2013-08-08 20:08:31', null);

-- ----------------------------
-- Records of tab_tipo_pessoa
-- ----------------------------
INSERT INTO `tab_tipo_pessoa` VALUES ('1', 'Pessoa Fisica');
INSERT INTO `tab_tipo_pessoa` VALUES ('2', 'Pessoa Juridica');