<?php /* Smarty version 2.6.14, created on 2013-11-12 16:26:51
         compiled from tplLista.htm */ ?>
<!-- BEGIN PAGE CONTAINER-->			<div class="container-fluid">    <!-- BEGIN PAGE HEADER-->    <div class="row-fluid">        <div class="span12">            <!-- BEGIN PAGE TITLE & BREADCRUMB-->			            <h3 class="page-title">                <?php echo $this->_tpl_vars['NomModulo']; ?>
            </h3>            <ul class="breadcrumb">                <li>                    <i class="icon-home"></i>                    <a href="index.php">Home</a>                     <i class="icon-angle-right"></i>                </li>                <li>                    <a href="#"><?php echo $this->_tpl_vars['NomModulo']; ?>
</a>                                    </li>                            </ul>            <!-- END PAGE TITLE & BREADCRUMB-->        </div>    </div>    <!-- END PAGE HEADER-->    <!-- BEGIN PAGE CONTENT--><div class="row-fluid">    <div class="span6 responsive" data-tablet="span12 fix-offset" data-desktop="span6">        <!-- BEGIN EXAMPLE TABLE PORTLET-->        <div class="portlet box grey">            <div class="portlet-title">                <h4><i class="icon-globe"></i><?php echo $this->_tpl_vars['NomModulo']; ?>
</h4>		                <div class="actions">		                        <?php if ($this->_tpl_vars['display_cadastro']): ?>                        <a href="Visualiza.php?modulo=<?php echo $this->_tpl_vars['modulo']; ?>
&acao=<?php echo $this->_tpl_vars['CADASTRAR']; ?>
" class="btn blue"><i class="icon-pencil"></i> Adicionar novo</a>                    <?php endif; ?>                    <!--<div class="btn-group">                        <a class="btn green" href="#" data-toggle="dropdown">                            <i class="icon-cogs"></i> A&ccedil;&otilde;es                            <i class="icon-angle-down"></i>                        </a>                        <ul class="dropdown-menu pull-right">                            <li><a href="#"><i class="icon-download"></i> Imprimir</a></li>                            <li><a href="#"><i class="icon-download-alt"></i> Exportar em PDF</a></li>                            <li><a href="#"><i class="icon-download-alt"></i> Exportar em Excel</a></li>                            <?php if ($this->_tpl_vars['display_edit']): ?><li><a href="#"><i class="icon-pencil"></i> Editar</a></li><?php endif; ?>                            <?php if ($this->_tpl_vars['display_excluir']): ?><li><a href="#"><i class="icon-trash"></i> Deletar</a></li><?php endif; ?>                            <li><a href="#"><i class="icon-ban-circle"></i> Excluir</a></li>                            <li class="divider"></li>                            <li><a href="#"><i class="i"></i> Make admin</a></li>                        </ul>			                    </div>-->                                     </div> 		            </div>            <div class="portlet-body">                <table class="table table-striped table-bordered table-hover" id="sample_2">		    <input type="hidden" name="num_modulo" id="num_modulo" value="<?php echo $this->_tpl_vars['modulo']; ?>
" >                    <thead>                        <tr>                            <th style="width:8px;">				<input type="checkbox" class="group-checkable" data-set="#sample_2 .checkboxes" />			    </th>                            <?php $_from = $this->_tpl_vars['grid_config']['colNames']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['lst']):
?>				<th class="hidden-480"><?php echo $this->_tpl_vars['lst']; ?>
</th>                                                            <?php endforeach; endif; unset($_from); ?>                        </tr>                    </thead>                    <tbody id="listGrid">                        <?php $_from = $this->_tpl_vars['listtable']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['k'] => $this->_tpl_vars['lst']):
?>                            <tr class="odd gradeX" >                                                                <?php $_from = $this->_tpl_vars['lst']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['item']):
?>                                    <?php if ($this->_tpl_vars['key'] == 0): ?>                                        <?php if ($this->_tpl_vars['display_visualizar']): ?>					<td><input type="checkbox" class="checkboxes" value="1" id="<?php echo $this->_tpl_vars['item']; ?>
" /></td>                                        <td><a class="btn mini" href="Visualiza.php?modulo=<?php echo $this->_tpl_vars['modulo']; ?>
&id=<?php echo $this->_tpl_vars['item']; ?>
&acao=1" title="Visualizar"><?php echo $this->_tpl_vars['item']; ?>
</a></td>                                        <?php else: ?>                                        <td><?php echo $this->_tpl_vars['item']; ?>
</td>                                         <?php endif; ?>                                                                        <?php else: ?>                                                                      <td><?php echo $this->_tpl_vars['item']; ?>
</td>                                           <?php endif; ?>                                <?php endforeach; endif; unset($_from); ?>                            </tr>                            <?php endforeach; endif; unset($_from); ?>                    </tbody>                </table>		<?php if ($this->_tpl_vars['display_excluir'] || $this->_tpl_vars['display_cadastro']): ?>		<div>			<?php if ($this->_tpl_vars['display_excluir']): ?>			<a class="btn mini red" id="remove_selected" href="javascript:delListData('<?php echo $this->_tpl_vars['modulo']; ?>
');"><i class="icon-trash"></i> Remover selecionados</a>			<?php endif; ?>					</div>				<?php endif; ?>		            </div>        </div>        <!-- END EXAMPLE TABLE PORTLET-->    </div>    </div><!-- END PAGE CONTENT--></div><script language="javascript">var modulo = '<?php echo $this->_tpl_vars['modulo']; ?>
';<?php echo '/* Funcao responsavel por executar o excluir de Linha * @params: valor - ( int ) conteúdo para restrição do delete */function deleteLinha( valor ){	var dados = [{ chave : valor }];	if( confirm(\'Deseja realmente remover este registro?\') ){		$.post( \'../_ax/axRequest.php\', { modulo: modulo, method: \'excluir\', args: dados }, function( data ) {									if( typeof data == \'object\' && data.response.Error ) {					    if( data.response.Error.code == \'42000\')				alert(\'Nao foi possivel remover registro. Erro no sistema\');			    else{				if( data.response.Error.code == \'23000\')				    alert(\'Nao foi possovel excluir este registro, existem outras informacoes associadas a ele. \\nPor favor remover as dependencias e tentar novamente.\');						    }			}else{			    alert(\'Registro removido com sucesso\');			    location.reload();			}		}, \'json\');	}}</script>'; ?>
